### ISSUE TITLE
Turn off autorefresh by default

### ISSUE THREAD

**Issue by tallkid24** [agoldis/sorry-cypress#110]
The autorefresh is nice but every second its retrieving MBs of data which if you accidentally keep the dashboard up, will eat up your datacap. Would be nice if it was turned off by default and then you could switch it on.

![image](https://user-images.githubusercontent.com/52414395/88202681-d9912d00-cc0e-11ea-9534-c1a8df8b9615.png)

**Comment by agoldis** [comment]
😃  @jhicken FYI

**Comment by jhicken** [comment]
@agoldis should we add an env var for that? Or we could do a localstorrage setting in the UI. 

Thoughs?

**Comment by agoldis** [comment]
- env is too heavy - ppl will need to restart / redeploy the service
- local storage is a good option, but people will still need a UI control for that.

May be a toggle in the dashboard with `off` by default? 

@tallkid24 @jhicken  how does that sound to you?

**Comment by KyleThenTR** [comment]
Sounds good to me

**Comment by jhicken** [comment]
Yup sounds good.

**Comment by agoldis** [comment]
@jhicken I have temporary disabled polling for root view due #111 

I will work later polling-friendly pagination and toggle as discussed on #110

**Comment by agoldis** [comment]
Resolved by #122
