### ISSUE TITLE
Migrate the documentation to sorry-cypress.dev

### ISSUE THREAD

**Issue by agoldis** [agoldis/sorry-cypress#119]
The code is hosted at https://github.com/sorry-cypress/sorry-cypress.dev

This is the documentation structure I thought about. It greatly resembles what we already have at https://github.com/agoldis/sorry-cypress

- Introduction (features, badges, pitch gif)
- Demo (link to heroku)
- Quickstart 
- Terminology 
 - Director
    - Configuration
    - Execution Drivers
       - In-memory
       - MongoDB
     - Storage Drivers
        - Dummy
        - S3
        - Minio (@StefanS-O)

 - API (GraphQL)

 - Dashboard

- On-premise installation
  - Dockerfile
  - Heroku
  - AWS

- CI Guides
    - Jenkins
    - AWS codebuild A
    - AWS Code Build B

- Cypress agent
    - Manual config
    - CLI one-liners
    - Wrapper

- Development
  - Project structure
  - Behind the scenes
- FAQ

**Comment by StefanS-O** [comment]
@agoldis i can help

**Comment by coreyshirk** [comment]
@agoldis what are your thoughts on making a discord for the project?

**Comment by StefanS-O** [comment]
@coreyshirk there is already a Slack channel with not many participants. Maybe you can join there, or is there a specific reason why you prefer Discord?

**Comment by coreyshirk** [comment]
@StefanS-O didn't know there was a Slack channel, no need for Discord then

**Comment by StefanS-O** [comment]
@coreyshirk : https://join.slack.com/t/sorry-cypress/shared_invite/zt-eis1h6jl-tJELaD7q9UGEhMP8WHJOaw seems rather new :)

**Comment by agoldis** [comment]
https://sorry-cypress.dev
