### ISSUE TITLE
AWS S3 screenshot uploads not working

### ISSUE THREAD

**Issue by KyleThenTR** [agoldis/sorry-cypress#128]
Not sure if this is just something messed up with our configuration.. but all screenshot uploads to S3 suddenly stopped working a week ago or so. The console output just says "Failed uploading".

Our configuration is a little different, it's a private S3 bucket, but I've made sure to allow the Task role permissions to write to the S3 bucket (I even allowed the whole account and every single S3 action).

If more information is needed, let me know, I can provide more.

**Comment by lipt0n** [comment]
hi,
have the same error. my s3 bucket is public. error is:

<Error><Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the region 'us-east-1' is wrong; expecting 'us-west-2'</Message><Region>us-west-2</Region>

**Comment by agoldis** [comment]
@KyleThenTR  @lipt0n  What cypress version are you using?

**Comment by agoldis** [comment]
I have just checked the master branch and it all works fine. Same for the demo version  at https://sorry-cypress-demo.herokuapp.com/, which runs the most recent sorry-cypress version also works.

@KyleThenTR When you say "private" do you mean it has no public read? That shouldn't affect the write operations. Can you please run cypress in debug mode `DEBUG=cypress:*` to see the error details?

@lipt0n what is your `S3_REGION` and `S3_BUCKET` configuration? Googling it resembles [this issue](https://github.com/aws/aws-sdk-ruby/issues/690). You can explicitly set S3 DNS via (`S3_READ_URL_PREFIX`)[https://github.com/agoldis/sorry-cypress/blob/master/packages/director/src/screenshots/s3/s3.ts#L51:L51] (the name is actually misleading)

**Comment by lipt0n** [comment]
i did try setting S3_REGION and S3_READ_URL_PREFIX , but error is the same:
cypress:server:api request to url: PUT http://flipper-cypress-1182330490.us-west-2.elb.amazonaws.com:8080/instances/a82a594a-d7cb-44e9-ac95-2d3994841537 with params: {"body ....
.....
cypress:server:record failed to upload artifact { file: 
....

<Code>AuthorizationQueryParametersError</Code><Message>Error parsing the X-Amz-Credential parameter; the region 'us-east-1' is wrong; expecting 'us-west-2'</Message><Region>us-west-2</Region>

**Comment by lipt0n** [comment]
or is this something to setup in sorry cypress director ?  setting this up in cypress doesn't change a thing

**Comment by lipt0n** [comment]
ok, I.ve got it
after setting S3_REGION env in director it starts working. 
thx for help!

**Comment by KyleThenTR** [comment]
@agoldis looks like they are uploading now, it's just not showing up on sorry cypress. We are on Cypress v5.0.0. Could that be the reason the screenshots stopped showing?

**Comment by agoldis** [comment]
@KyleThenTR Are you able to access the S3 image by just typing the uploaded image URL? I believe it has something to do with the way you set permissions on S3.

**Comment by KyleThenTR** [comment]
@agoldis no I can't. I think it does have to do with the fact the the bucket is private and I can't set the bucket policy to be allowed for *. Now that I think about it, the bucket got changed to private the other week and that's when it stopped working. Don't think I can change that though since it's policy now

**Comment by KyleThenTR** [comment]
I suppose I could setup a cloudfront distribution to be able to access those images and then set that S3_READ_URL_PREFIX param

**Comment by KyleThenTR** [comment]
@agoldis I fixed this. I had to set the S3_ACL env var to private and then add a cloudfront distribution in front of the S3 bucket, and then updated the S3_READ_URL_PREFIX to the cloudfront distribution URL. This can be closed.
