### ISSUE TITLE
cypress 5 new error field

### ISSUE THREAD

**Issue by Ahton89** [agoldis/sorry-cypress#135]
In last cypress package (5.1.0) error field named is displayError and dashboard not show error message in failed tests. 
Need support this for latest versions dashboard. 
`"tests" : [
			{
				"testId" : "r4",
				"title" : [
					"All Tools",
					"Есть данные",
					"Видим элементов = 20"
				],
				"state" : "failed",
				"body" : "function () {\n      cy.get('[data-cy^=all_tools__item--]').should('have.length', inputAllTools.records.length + 10);\n    }",
				"displayError" : "AssertionError: Timed out retrying: Not enough elements found. Found '10', expected '20'.\n    at Context.eval (http://localhost/__cypress/tests?p=cypress/integration/all_tools.spec.js:171:46)",
				"attempts" : [
					{
						"state" : "failed",
						"error" : {
							"name" : "AssertionError",
							"message" : "Timed out retrying: Not enough elements found. Found '10', expected '20'.",
							"stack" : "    at Context.eval (http://localhost/__cypress/tests?p=cypress/integration/all_tools.spec.js:171:46)"
						},`

**Comment by agoldis** [comment]
Sure! This has been already reported at #125. Closing this one as a duplicate.
