### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by M0dM** [agoldis/sorry-cypress#15]
Hi,

What do you think about writing a docker compose file to run all 3 packages in a single command locally ?

Regards,

**Comment by agoldis** [comment]
Good idea!

Do you mean for dev or for deployment? 

We already have this one, I use it for dev: https://github.com/agoldis/sorry-cypress/blob/master/docker-compose.yml

But it only runs 2 backend packages - I couldn't plug the web dashboard into docker-compose in a convenient way.

**Comment by M0dM** [comment]
I mean, if a new user wants to test sorry-cypress he should be able to use a docker compose file with docker images pulled from docker hub to start start testing it in 2 minutes.
