### ISSUE TITLE
Option to override screenshot bucket url

### ISSUE THREAD

**Issue by ifulfilment** [agoldis/sorry-cypress#20]
sorry-cypress/blob/master/packages/director/src/screenshots/s3/s3.ts

line 5

allow override of AWS url from config file

import { S3_BUCKET } from './config';
import { S3_URL } from './config'; // default s3.amazonaws.com
import { S3SignedUploadResult } from './types';

const BUCKET_URL = `https://${S3_BUCKET}.${S3_URL}`;

This will allow passing of EU url's  (s3.eu-north-1.amazonaws.com) and fix the redirect error when uploading screenshots.

**Comment by ifulfilment** [comment]
Hi
I've done a bit more digging on this and my issue maybe with a newly created bucket on s3 (i only work with google normally). 

I had to add the region to the s3 setup as well to get the screenshots to upload,
const s3 = new aws.S3({
  region: "eu-north-1",
  signatureVersion: 'v4'
});

having the ability to pass the region through would be good for DNS?

**Comment by agoldis** [comment]
@ifulfilment thanks for proposing the enhancement.
I have tested using `sorry-cypress-nord` S3 bucket from `eu-north-1` region. Setting the region explicitly actually resolves the issue.
