### ISSUE TITLE
Dashboard fails to load when cypress is run in docker (e.g. on CI) due to missing git information

### ISSUE THREAD

**Issue by TomaszG** [agoldis/sorry-cypress#21]
Dashboard fails to load and displays "Error :(" if some of git related information is missing in the recorded job. The error is a result of another error coming from the graphql api:

`Cannot return null for non-nullable field Commit.sha.`
or
`Cannot return null for non-nullable field Commit.remoteOrigin.`

This may happen when Cypress is run in docker where there's no .git directory and environment variables to fetch the information from. This may also happen for some specific CI providers where some git information cannot be extracted by the Cypress test runners and it defaults to `null` (see https://github.com/cypress-io/cypress/blob/00a7e69ed267196c778bc3b22f6f8f0e28c30266/packages/server/lib/util/ci_provider.js#L441)

**Comment by agoldis** [comment]
@TomaszG thanks for reporting that! Fixed in https://github.com/agoldis/sorry-cypress/releases/tag/v0.0.3
