### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by kennetPerez** [agoldis/sorry-cypress#23]
Hey, @agoldis do you have planned to add the function to upload videos and show it in the dashboard? Right now if we have enabled the videos function are being recording and saving into the directory where we are running, it would be great if you have planned to add something similar to Screenshot Driver but in this case for videos.
![image](https://user-images.githubusercontent.com/5490777/71922256-3edc6f80-3150-11ea-8398-c7db0d7d3e7b.png)

**Comment by agoldis** [comment]
@kennetPerez you've got it, please check out #27

**Comment by kennetPerez** [comment]
@agoldis this is great men, I loved this project, you're amazing, I expect to collaborate in this project in the future.
