### ISSUE TITLE
Load More button on Dashboard skips one recorded run

### ISSUE THREAD

**Issue by TomaszG** [agoldis/sorry-cypress#28]
It seems that the **Load More** button on the Dashboard always skips one record. Let's say that we have the following runs recorded:
`[1, 2, 3, 4, 5, 6, 7, 8]`
By default, `[6, 7, 8]` are displayed and the **Load More** button, however, when it's clicked then the following runs are displayed: `[2, 3, 4, 6, 7, 8]`. Apparently, run number `5` is omitted and it cannot be displayed.

**Comment by agoldis** [comment]
Good catch!

**Comment by agoldis** [comment]
Resolved in https://github.com/agoldis/sorry-cypress/releases/tag/v0.1.1
Thanks for raising the issue!
