### ISSUE TITLE
Tests runs but not shown on the dashboard!

### ISSUE THREAD

**Issue by mrvarmazyar** [agoldis/sorry-cypress#29]
Hi Agoldis,

I run the cypress test every 30 mins on the development environment and after finishing I face on with this scene:
Dev-Auto-01222020121731-57701
Tests: 0
Passes: 0
Failures: 0
Pending: 0
Skipped: 0
Spec files
Overall: 14
Claimed: 0

So please tell me know how can I fix it?

Thanks

**Comment by agoldis** [comment]
Are you getting this result for every run or for some specific, single run? 

When running the tests, cypress agents do two API calls:

1. send list of specs, `ci-build-id` and other CLI parameters. Based on that info,  the agent receives "runId" and "machineId"

2. send "machineId" and "runId" and get the spec name to execute. Before returning the spec, server (the director) marks it as "claimed". 

Based on your output, no agent made the second call to "claim" a spec. Probably the agent halted before issues the second call? 

It's hard to tell more than that based on the data you provided :)

**Comment by agoldis** [comment]
@mrvarmazyar hey, I am thinking about closing that issue, would you mind?
