### ISSUE TITLE
Error: Network error: Failed to fetch

### ISSUE THREAD

**Issue by jpdentone** [agoldis/sorry-cypress#32]
Hi

I'm trying to set this up on a AWS ec2 instance with external mongodb cluster but when I go to the dashboard URL is see a message "Error: Network error: Failed to fetch"

I've tested the same docker-compose.yml file in my localhost and it works fine but it doesnt on the ec2 instance. 
Logs seems ok 

> root@cypress:/opt/cypress# docker-compose -f docker-compose.yml up
Recreating cypress_director_1 ... done
Recreating cypress_api_1      ... done
Recreating cypress_dashboard_1 ... done
Attaching to cypress_director_1, cypress_api_1, cypress_dashboard_1
api_1        |
api_1        | > @sorry-cypress/api@0.1.1 start /app
api_1        | > node ./dist/
api_1        |
api_1        | 🚀 Apollo server ready at http://localhost:4000/
director_1   |
director_1   | > @sorry-cypress/director@0.1.1 start /app
director_1   | > node ./dist/
director_1   |
director_1   | Initializing "stateful-mongo" execution driver...
director_1   | (node:25) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
director_1   | Successfully connected to MongoDB server
director_1   | Initializing "s3" screenshots driver...
director_1   | Listening on 1234...
dashboard_1  |
dashboard_1  | > @sorry-cypress/dashboard@0.1.1 start /app
dashboard_1  | > node ./server
dashboard_1  |
dashboard_1  | Listening on 8080...
dashboard_1  | ℹ ｢wdm｣: Hash: 1603e534a929b7d4ab0a
dashboard_1  | Version: webpack 4.41.5
dashboard_1  | Time: 3727ms
dashboard_1  | Built at: 02/18/2020 2:56:56 PM
dashboard_1  |           Asset       Size  Chunks             Chunk Names
dashboard_1  |       index.mjs   3.44 MiB    main  [emitted]  main
dashboard_1  | views/index.ejs  728 bytes          [emitted]
dashboard_1  | Entrypoint main = index.mjs
dashboard_1  | [0] multi ./src/index.tsx 28 bytes {main} [built]
dashboard_1  | [./node_modules/@apollo/react-hooks/lib/react-hooks.esm.js] 30 KiB {main} [built]
dashboard_1  | [./node_modules/bold-ui/lib/index.js] 331 bytes {main} [built]
dashboard_1  | [./node_modules/react-dom/cjs/react-dom.development.js] 947 KiB {main} [built]
dashboard_1  | [./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
dashboard_1  | [./node_modules/react-router-dom/esm/react-router-dom.js] 9.76 KiB {main} [built]
dashboard_1  | [./node_modules/react/cjs/react.development.js] 72.7 KiB {main} [built]
dashboard_1  | [./node_modules/react/index.js] 190 bytes {main} [built]
dashboard_1  | [./src/Root.tsx] 2.02 KiB {main} [built]
dashboard_1  | [./src/components/layout/content.tsx] 648 bytes {main} [built]
dashboard_1  | [./src/components/layout/header.tsx] 1.38 KiB {main} [built]
dashboard_1  | [./src/index.tsx] 166 bytes {main} [built]
dashboard_1  | [./src/lib/apolloClient.ts] 1.23 KiB {main} [built]
dashboard_1  | [./src/theme/theme.ts] 1.32 KiB {main} [built]
dashboard_1  | [./src/views/InstanceDetailsView.tsx] 1.55 KiB {main} [built]
dashboard_1  |     + 743 hidden modules
dashboard_1  | Child HtmlWebpackCompiler:
dashboard_1  |                           Asset      Size               Chunks  Chunk Names
dashboard_1  |     __child-HtmlWebpackPlugin_0  5.02 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
dashboard_1  |     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
dashboard_1  |     [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 909 bytes {HtmlWebpackPlugin_0} [built]
dashboard_1  | ℹ ｢wdm｣: Compiled successfully.

any idea what could be the issue?

**Comment by jpdentone** [comment]
figured it out, issue was on aws side, sorry about this

**Comment by agoldis** [comment]
@jpdentone Hey! I am curious about different ways ppl set up the project on AWS. Would you agree to share your setup / configuration so I can use it in a guide / tutorial?
