### ISSUE TITLE
Specs show as Failed in the dashboard when they are skipped/pending

### ISSUE THREAD

**Issue by KyleThenTR** [agoldis/sorry-cypress#36]
If a test is skipped in Cypress using it.skip(), the tests show up as Pending result instead of Skipped and then show the spec as Failed

**Comment by agoldis** [comment]
FYI. 
https://github.com/cypress-io/cypress/issues/3092

**Comment by agoldis** [comment]
Released in https://github.com/agoldis/sorry-cypress/releases/tag/v0.2.1
