### ISSUE TITLE
GraphQL error: Cannot return null for non-nullable field 

### ISSUE THREAD

**Issue by agoldis** [agoldis/sorry-cypress#42]
@KyleThenTR reposting your comment as a new issue:

I did see a different error come up on the dashboard:
Error: GraphQL error: Cannot return null for non-nullable field InstanceResults.tests.

**Comment by agoldis** [comment]
@KyleThenTR I'll need more details for that
1. What is the api and dashboard version you're running?
2. What's the screen / URL are you trying to access?

**Comment by KyleThenTR** [comment]
0.2.1 and just trying to go to the main dashboard page to see a list of all my runs. It did end up clearing up so I'm wondering if something got put into the graphQL DB that wasn't correct. I wasn't sure how to query so I couldn't get any information from the API endpoint. Next time this happens I can if you happen to know what query I should run?

**Comment by agoldis** [comment]
Thanks @KyleThenTR, it is helpful. Seems like type definitions are not taking in account that not all data is available right away.
I will look into that further.

**Comment by agoldis** [comment]
@KyleThenTR to your question  

> what query I should run

If you open network tab, you'll see the query details in POST request to API.

All the queries are available in `*.graphql` files, e.g.:

https://github.com/agoldis/sorry-cypress/tree/master/packages/dashboard/src/views

You can access GraphQL interface directly by opening API service URL in browser.

**Comment by KyleThenTR** [comment]
![image](https://user-images.githubusercontent.com/52414395/76314421-c48db000-62a4-11ea-8927-d779105c3946.png)

I actually can still recreate if I page back far enough on the dashboard

**Comment by agoldis** [comment]
Fix released in https://github.com/agoldis/sorry-cypress/releases/tag/v0.2.3

**Comment by klaidaslekavicius** [comment]
Hello! I seem to get the same issue. `sorry-cypress` was deployed using AWS Cloudfront stack provided.

![Screenshot 2020-05-12 at 17 18 00](https://user-images.githubusercontent.com/36949465/81797686-ccbdd200-9517-11ea-9726-4e0f25a21ee9.png)

Seems that the issue is identical to the one provided here, and I think we have the latest version deployed. Dashboard starts showing "No data".

**Comment by mike-park** [comment]
Ditto using the latest docker images...

**Comment by agoldis** [comment]
should be resolved in https://github.com/agoldis/sorry-cypress/releases/tag/v0.4.1
