### ISSUE TITLE
Skipped test is not calculated and not displayed

### ISSUE THREAD

**Issue by pshynin** [agoldis/sorry-cypress#44]
if single test within spec file skipped it marked skipped within the spec file page however number of skipped tests remains 0 on either spec page or run page

**Comment by agoldis** [comment]
@pshynin what version are you running? I remember fixing similar problem at https://github.com/agoldis/sorry-cypress/issues/36

**Comment by pshynin** [comment]
Hey, I am using :latest image. Let me try to reproduce and add more specific details. 
by the way thanks for doing this! awesome project!
