### ISSUE TITLE
Provision to serve assests from private s3 buckets

### ISSUE THREAD

**Issue by xtroncode** [agoldis/sorry-cypress#48]
- the ACL used for generating upload url is `public-read` due to which upload fails for private buckets
- Can we make the `readUrl` configurable such that we can serve s3 assets from a private bucket via a proxy or can we have signed get urls in the dashboard ?

**Comment by agoldis** [comment]
@xtroncode thanks for opening the request!

Should be configurable in https://github.com/agoldis/sorry-cypress/releases/tag/v0.2.4
also updated the documentation https://github.com/agoldis/sorry-cypress/wiki/S3-screenshot-driver

**Comment by agoldis** [comment]
@xtroncode sorry, `2.0.4` is buggy, releasing `2.0.5`
