### ISSUE TITLE
version in docker-compose unsupported

### ISSUE THREAD

**Issue by zx86496790** [agoldis/sorry-cypress#50]
new to this. got an error saying Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the services key, or omit the version key and place your service definitions at the root of the file to use version 1.
please help

**Comment by agoldis** [comment]
Welcome @zx86496790! 

As per https://docs.docker.com/compose/compose-file/compose-versioning/ you'll need to upgrade your docker-compose to version gte `18.02.0`.

Tell me if that worked!

**Comment by zx86496790** [comment]
it works now. thank you very much. issue closed
