### ISSUE TITLE
Sometimes a spec or 2 doesn't get picked up and ran - stuck in pending

### ISSUE THREAD

**Issue by tallkid24** [agoldis/sorry-cypress#56]
I apologize for an issue without any repro steps, but not really sure how to repro it. I am running a codebuild with 5 Cypress parallel commands on it. Sometimes, there will be a spec or 2 that is stuck on the Pending state on the sorry cypress dashboard. When I search for the spec in the Codebuild logs, there is no mention of it. So something must be blocking it from getting picked up?

**Comment by agoldis** [comment]
@tallkid24 no need to apologize! 
It would be helpful, though, to get more data about the issue - ideally, it'd be log traces from cypress agents and from the director service.

Also, you can directly access the mongo DB to see what is was stored by the director.

It's quite hard to troubleshoot those issue if those are intermittent, I understand.

I can tell that I have been running sorry-cypress for my employer for more than a year now (before it was published on github), we use circleCI parallelized  environment of 100 workers to run ~100 spec files with 300+ individual tests, I didn't see the issue you described :)

But let's try to figure it out!

**Comment by tallkid24** [comment]
@agoldis How would I query the mongo DB to see what was stored for the run? I still do have the ci build ID from the cypress run so I assume that is stored?

**Comment by tallkid24** [comment]
Oh, actually I think I see the possible issue digging into the logs further. The cypress run ended with an error exit code

`Failed to connect to Chrome, retrying in 1 second (attempt 32/32)`

`Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 20 seconds.`

and then it shows the cypress command exiting with status code 1, which ends up failing all of my cypress runners.

**Comment by tallkid24** [comment]
So thats for that codebuild failure, but there have been instances where the logs just stop for one of the running instances of the cypress run, which makes me think it could possibly be a memory issue in the codebuild

**Comment by agoldis** [comment]
If you run on AWS, you'll need to open network access to the underlying mongodb instance, as soon as you expose a network port, you can use https://www.mongodb.com/products/compass or https://robomongo.org/ to explore the data. 

The data structure is very intuitive, I think you can just read it.

Another options is use GraphQL explorer - it is accessible just by accessing API service. It doesn't show all the data, though.

**Comment by agoldis** [comment]
@tallkid24 can I close that issue?

**Comment by tallkid24** [comment]
Yes I think so.
