### ISSUE TITLE
Dashboard displays no data in Linux but stores videos in Amazon S3 successfully

### ISSUE THREAD

**Issue by danielvianna** [agoldis/sorry-cypress#66]
**Windows is fine, NO problems at all
But In Digital Ocean CentOs and Ubuntu, I see no data**

![image](https://user-images.githubusercontent.com/7416070/80618711-bc82fe80-8a11-11ea-925d-568155d91943.png)

Steps to reproduce the error:

1-Use One-Click install Docker in Digital Ocean (Ubuntu Only)

2-Update all tools
Docker version 19.03.1, build 74b1e89
Docker-compose version 1.25.5
Ubuntu / VERSION=18.04.3 LTS (Bionic Beaver)

3-Install Sorry Cypress 0.2.3 with my S3 credentials

3-Run docker-compose -f docker-compose.full.yml

4-Run Cypress on a different machine with app.yml pointing to Digital Ocean. Successful upload. 
Note: Amazon S3 IS receiving the movies

**Results:**

![image](https://user-images.githubusercontent.com/7416070/80618471-6ca43780-8a11-11ea-8d92-fe545e5ed7ed.png)

**Error messages on Chrome Console:**
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/bold-ui/lib/components/Tabs/Tabs.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
http://localhost:4000/:1%20Failed%20to%20load%20resource:%20net::ERR_CONNECTION_REFUSED
_Other error messages are in the screenshot but they are similar_

**Server log:**

docker-compose -f docker-compose.full.yml up

Creating network "sorrycypress_default" with the default driver
Creating sorrycypress_mongo_1 ... done                                                                                                                                                                  Creating sorrycypress_director_1 ... done                                                                                                                                                               Creating sorrycypress_api_1      ... done                                                                                                                                                               Creating sorrycypress_dashboard_1 ... done                                                                                                                                                              Attaching to sorrycypress_mongo_1, sorrycypress_director_1, sorrycypress_api_1, sorrycypress_dashboard_1
mongo_1      | 2020-04-29T04:36:34.611+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1      | 2020-04-29T04:36:34.619+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=6896398ced55
mongo_1      | 2020-04-29T04:36:34.620+0000 I CONTROL  [initandlisten] db version v4.0.18
mongo_1      | 2020-04-29T04:36:34.621+0000 I CONTROL  [initandlisten] git version: 6883bdfb8b8cff32176b1fd176df04da9165fd67
mongo_1      | 2020-04-29T04:36:34.621+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo_1      | 2020-04-29T04:36:34.621+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1      | 2020-04-29T04:36:34.621+0000 I CONTROL  [initandlisten] modules: none
mongo_1      | 2020-04-29T04:36:34.621+0000 I CONTROL  [initandlisten] build environment:
mongo_1      | 2020-04-29T04:36:34.621+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo_1      | 2020-04-29T04:36:34.621+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1      | 2020-04-29T04:36:34.621+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1      | 2020-04-29T04:36:34.622+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
director_1   |
director_1   | > @sorry-cypress/director@0.2.6 start /app
director_1   | > node ./dist/
director_1   |
mongo_1      | 2020-04-29T04:36:34.624+0000 I STORAGE  [initandlisten]
mongo_1      | 2020-04-29T04:36:34.625+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1      | 2020-04-29T04:36:34.625+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1      | 2020-04-29T04:36:34.625+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=484M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongo_1      | 2020-04-29T04:36:36.458+0000 I STORAGE  [initandlisten] WiredTiger message [1588134996:458101][1:0x7f132fd72a80], txn-recover: Set global recovery timestamp: 0
mongo_1      | 2020-04-29T04:36:36.474+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo_1      | 2020-04-29T04:36:36.492+0000 I CONTROL  [initandlisten]
mongo_1      | 2020-04-29T04:36:36.492+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1      | 2020-04-29T04:36:36.492+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1      | 2020-04-29T04:36:36.492+0000 I CONTROL  [initandlisten]
mongo_1      | 2020-04-29T04:36:36.492+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: c8f84b59-b64f-4fd6-a731-ad938a6ca208
mongo_1      | 2020-04-29T04:36:36.506+0000 I SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
mongo_1      | 2020-04-29T04:36:36.506+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.0
mongo_1      | 2020-04-29T04:36:36.507+0000 I SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
mongo_1      | 2020-04-29T04:36:36.507+0000 I SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
mongo_1      | 2020-04-29T04:36:36.507+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 26f76b08-1db8-41ee-a63b-6283948c5a3a
mongo_1      | 2020-04-29T04:36:36.520+0000 I SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
mongo_1      | 2020-04-29T04:36:36.520+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
api_1        |
api_1        | > @sorry-cypress/api@0.2.6 start /app
api_1        | > node ./dist/
api_1        |
mongo_1      | 2020-04-29T04:36:36.525+0000 I SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
mongo_1      | 2020-04-29T04:36:36.525+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: 026fb069-4c60-48a0-9d0f-6d0a851d6b64
mongo_1      | 2020-04-29T04:36:36.526+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mongo_1      | 2020-04-29T04:36:36.549+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
mongo_1      | 2020-04-29T04:36:36.549+0000 I INDEX    [LogicalSessionCacheRefresh]      building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2020-04-29T04:36:36.549+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2020-04-29T04:36:36.550+0000 I SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
mongo_1      | 2020-04-29T04:36:37.000+0000 I SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
dashboard_1  |
dashboard_1  | > @sorry-cypress/dashboard@0.2.6 start /app
dashboard_1  | > node ./server
dashboard_1  |
director_1   | Initializing "stateful-mongo" execution driver...
director_1   | (node:25) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
mongo_1      | 2020-04-29T04:36:41.023+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:58592 #1 (1 connection now open)
mongo_1      | 2020-04-29T04:36:41.062+0000 I NETWORK  [conn1] received client metadata from 172.18.0.3:58592 conn1: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-58-generic" }, platform: "'Node.js v10.19.0, LE (legacy)" }
director_1   | Successfully connected to MongoDB server
director_1   | Initializing "s3" screenshots driver...
mongo_1      | 2020-04-29T04:36:41.934+0000 I STORAGE  [conn1] createCollection: sorry-cypress.runs with generated UUID: 3eb2f85d-0b16-43d6-890c-8685653fdc5e
director_1   | Listening on 1234...
mongo_1      | 2020-04-29T04:36:41.938+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:58596 #2 (2 connections now open)
mongo_1      | 2020-04-29T04:36:41.939+0000 I NETWORK  [conn2] received client metadata from 172.18.0.3:58596 conn2: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-58-generic" }, platform: "'Node.js v10.19.0, LE (legacy)" }
mongo_1      | 2020-04-29T04:36:41.949+0000 I SHARDING [conn1] Marking collection sorry-cypress.runs as collection version: <unsharded>
mongo_1      | 2020-04-29T04:36:41.956+0000 I INDEX    [conn1] build index on: sorry-cypress.runs properties: { v: 2, unique: true, key: { runId: 1 }, name: "runId_1", ns: "sorry-cypress.runs" }
mongo_1      | 2020-04-29T04:36:41.956+0000 I INDEX    [conn1]   building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2020-04-29T04:36:41.957+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2020-04-29T04:36:41.958+0000 I STORAGE  [conn2] createCollection: sorry-cypress.instances with generated UUID: 9b525126-820f-4ee2-9e1d-a555afd343f3
mongo_1      | 2020-04-29T04:36:41.973+0000 I SHARDING [conn2] Marking collection sorry-cypress.instances as collection version: <unsharded>
mongo_1      | 2020-04-29T04:36:41.982+0000 I INDEX    [conn2] build index on: sorry-cypress.instances properties: { v: 2, unique: true, key: { instanceId: 1 }, name: "instanceId_1", ns: "sorry-cypress.instances" }
mongo_1      | 2020-04-29T04:36:41.982+0000 I INDEX    [conn2]   building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2020-04-29T04:36:41.984+0000 I INDEX    [conn2] build index done.  scanned 0 total records. 0 secs
api_1        | 🚀 Apollo server ready at http://localhost:4000/
dashboard_1  | Listening on 8080...
dashboard_1  | ℹ ｢wdm｣: Hash: 4701af221de2d5e4b7e4
dashboard_1  | Version: webpack 4.43.0
dashboard_1  | Time: 6363ms
dashboard_1  | Built at: 04/29/2020 4:36:49 AM
dashboard_1  |           Asset       Size  Chunks             Chunk Names
dashboard_1  |       index.mjs   3.26 MiB    main  [emitted]  main
dashboard_1  | views/index.ejs  728 bytes          [emitted]
dashboard_1  | Entrypoint main = index.mjs
dashboard_1  | [0] multi ./src/index.tsx 28 bytes {main} [built]
dashboard_1  | [./node_modules/@apollo/react-hooks/lib/react-hooks.esm.js] 30.4 KiB {main} [built]
dashboard_1  | [./node_modules/bold-ui/lib/index.js] 331 bytes {main} [built]
dashboard_1  | [./node_modules/react-dom/cjs/react-dom.development.js] 839 KiB {main} [built]
dashboard_1  | [./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
dashboard_1  | [./node_modules/react-router-dom/esm/react-router-dom.js] 9.76 KiB {main} [built]
dashboard_1  | [./node_modules/react/cjs/react.development.js] 59.2 KiB {main} [built]
dashboard_1  | [./node_modules/react/index.js] 190 bytes {main} [built]
dashboard_1  | [./src/Root.tsx] 2.19 KiB {main} [built]
dashboard_1  | [./src/components/layout/content.tsx] 661 bytes {main} [built]
dashboard_1  | [./src/components/layout/header.tsx] 1.43 KiB {main} [built]
dashboard_1  | [./src/index.tsx] 180 bytes {main} [built]
dashboard_1  | [./src/lib/apolloClient.ts] 1.23 KiB {main} [built]
dashboard_1  | [./src/theme/theme.ts] 1.32 KiB {main} [built]
dashboard_1  | [./src/views/InstanceDetailsView.tsx] 1.66 KiB {main} [built]
dashboard_1  |     + 718 hidden modules
dashboard_1  | Child HtmlWebpackCompiler:
dashboard_1  |                           Asset      Size               Chunks  Chunk Names
dashboard_1  |     __child-HtmlWebpackPlugin_0  5.02 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
dashboard_1  |     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
dashboard_1  |     [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 909 bytes {HtmlWebpackPlugin_0} [built]
dashboard_1  | ℹ ｢wdm｣: Compiled successfully.
director_1   | >> Machine is asking to join a run { recordKey: 'xxxxxxxx-xxxx-xxxx-a647-62ec2f273de5',
director_1   |   ciBuildId: '126' }
director_1   | >> Machine is joining a run { ciBuildId: '126' }
director_1   | << Responding to machine { groupId: 'win32-10.0.18363-126',
director_1   |   machineId: 'b27c5f44-18c5-4e2a-9a89-b9357e02836c',
director_1   |   runId: 'ba4b1f6efbdb7bd7c328510115f8fab9',
director_1   |   runUrl: 'http://localhost:8080/run/ba4b1f6efbdb7bd7c328510115f8fab9',
director_1   |   warnings: [] }
director_1   | >> Machine is requesting a new task { runId: 'ba4b1f6efbdb7bd7c328510115f8fab9',
director_1   |   machineId: 'b27c5f44-18c5-4e2a-9a89-b9357e02836c',
director_1   |   groupId: 'win32-10.0.18363-126' }
director_1   | << Sending new task to machine { spec:
director_1   |    'cypress\\integration\\moa-customer-portal\\08-login\\8a-moacustomer-login-registration.js',
director_1   |   instanceId: '3db11dc0-4ffc-4584-8511-e823876fc5b1',
director_1   |   claimed: false }
director_1   | >> Received instance result { instanceId: '3db11dc0-4ffc-4584-8511-e823876fc5b1' }
director_1   | << Sending assets upload URLs { instanceId: '3db11dc0-4ffc-4584-8511-e823876fc5b1',
director_1   |   screenshotUploadUrls: [],
director_1   |   videoUploadInstructions:
director_1   |    { readUrl:
director_1   |       'https://REMOVEDBUCKETADDRESSBEFOREPOSTING.s3.amazonaws.com/3db11dc0-4ffc-4584-8511-e823876fc5b1.mp4',
director_1   |      uploadUrl:
director_1   |       'https://REMOVEDBUCKETADDRESSBEFOREPOSTING.s3.ca-central-1.amazonaws.com/3db11dc0-4ffc-4584-8511-e823876fc5b1.mp4?Content-Type=video%2Fmp4&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REMOVEDCREDENTIALBEFOREPOSTING%2F20200429%2Fca-central-1%2Fs3%2Faws4_request&X-Amz-Date=20200429T044718Z&X-Amz-Expires=90&X-Amz-Signature=8fc15921c1842dc0e13636f23de78b4d3f182a76c80c0b5ecd4080b1c14e6a87&X-Amz-SignedHeaders=host%3Bx-amz-acl&x-amz-acl=public-read' } }
director_1   | >> [not implemented] Received stdout for instance { instanceId: '3db11dc0-4ffc-4584-8511-e823876fc5b1' }
director_1   | >> Machine is requesting a new task { runId: 'ba4b1f6efbdb7bd7c328510115f8fab9',
director_1   |   machineId: 'b27c5f44-18c5-4e2a-9a89-b9357e02836c',
director_1   |   groupId: 'win32-10.0.18363-126' }
director_1   | << Sending new task to machine { spec:
director_1   |    'cypress\\integration\\moa-customer-portal\\08-login\\8b-moacustomer-login-forgot-password-reset.js',
director_1   |   instanceId: 'b83a4e75-ad95-4e87-84e1-127dd249f218',
director_1   |   claimed: false }
director_1   | >> Received instance result { instanceId: 'b83a4e75-ad95-4e87-84e1-127dd249f218' }
director_1   | << Sending assets upload URLs { instanceId: 'b83a4e75-ad95-4e87-84e1-127dd249f218',
director_1   |   screenshotUploadUrls:
director_1   |    [ { readUrl:
director_1   |         'https://REMOVEDBUCKETADDRESSBEFOREPOSTING.s3.amazonaws.com/a5147610c6743e8939475bc9771e71d8.png',
director_1   |        uploadUrl:
director_1   |         'https://REMOVEDBUCKETADDRESSBEFOREPOSTING.s3.ca-central-1.amazonaws.com/a5147610c6743e8939475bc9771e71d8.png?Content-Type=image%2Fpng&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REMOVEDCREDENTIALBEFOREPOSTING%2F20200429%2Fca-central-1%2Fs3%2Faws4_request&X-Amz-Date=20200429T045007Z&X-Amz-Expires=60&X-Amz-Signature=688eebfa307f300cb4c31449fbaa7722d4e9a84b71f79d0a76ba9887036a6d75&X-Amz-SignedHeaders=host%3Bx-amz-acl&x-amz-acl=public-read',
director_1   |        screenshotId: 'j3htt' } ],
director_1   |   videoUploadInstructions:
director_1   |    { readUrl:
director_1   |       'https://REMOVEDBUCKETADDRESSBEFOREPOSTING.s3.amazonaws.com/b83a4e75-ad95-4e87-84e1-127dd249f218.mp4',
director_1   |      uploadUrl:
director_1   |       'https://REMOVEDBUCKETADDRESSBEFOREPOSTING.s3.ca-central-1.amazonaws.com/b83a4e75-ad95-4e87-84e1-127dd249f218.mp4?Content-Type=video%2Fmp4&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REMOVEDCREDENTIALBEFOREPOSTING%2F20200429%2Fca-central-1%2Fs3%2Faws4_request&X-Amz-Date=20200429T045007Z&X-Amz-Expires=90&X-Amz-Signature=d61792e8fc3996dc93107faf350dcfc53cf3adff222dfe658aea1bd88922237b&X-Amz-SignedHeaders=host%3Bx-amz-acl&x-amz-acl=public-read' } }
director_1   | >> [not implemented] Received stdout for instance { instanceId: 'b83a4e75-ad95-4e87-84e1-127dd249f218' }
director_1   | >> Machine is requesting a new task { runId: 'ba4b1f6efbdb7bd7c328510115f8fab9',
director_1   |   machineId: 'b27c5f44-18c5-4e2a-9a89-b9357e02836c',
director_1   |   groupId: 'win32-10.0.18363-126' }
director_1   | << Sending new task to machine { spec:
director_1   |    'cypress\\integration\\moa-customer-portal\\08-login\\8c-moacustomer-login-sign-in-sign-out.js .js',
director_1   |   instanceId: '7b8dabaa-5f22-4d01-b32f-5bbbb6b74f96',
director_1   |   claimed: false }
director_1   | >> Received instance result { instanceId: '7b8dabaa-5f22-4d01-b32f-5bbbb6b74f96' }
director_1   | << Sending assets upload URLs { instanceId: '7b8dabaa-5f22-4d01-b32f-5bbbb6b74f96',
director_1   |   screenshotUploadUrls: [],
director_1   |   videoUploadInstructions:
director_1   |    { readUrl:
director_1   |       'https://REMOVEDBUCKETADDRESSBEFOREPOSTING.s3.amazonaws.com/7b8dabaa-5f22-4d01-b32f-5bbbb6b74f96.mp4',
director_1   |      uploadUrl:
director_1   |       'https://REMOVEDBUCKETADDRESSBEFOREPOSTING.s3.ca-central-1.amazonaws.com/7b8dabaa-5f22-4d01-b32f-5bbbb6b74f96.mp4?Content-Type=video%2Fmp4&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REMOVEDCREDENTIALBEFOREPOSTING%2F20200429%2Fca-central-1%2Fs3%2Faws4_request&X-Amz-Date=20200429T045028Z&X-Amz-Expires=90&X-Amz-Signature=6cb8108f81ee15828a13c8a473dea1b5d474d5299b8f1d9f3a99dfdefba5c8d1&X-Amz-SignedHeaders=host%3Bx-amz-acl&x-amz-acl=public-read' } }
director_1   | >> [not implemented] Received stdout for instance { instanceId: '7b8dabaa-5f22-4d01-b32f-5bbbb6b74f96' }
director_1   | >> Machine is requesting a new task { runId: 'ba4b1f6efbdb7bd7c328510115f8fab9',
director_1   |   machineId: 'b27c5f44-18c5-4e2a-9a89-b9357e02836c',
director_1   |   groupId: 'win32-10.0.18363-126' }
director_1   | << All tasks claimed { runId: 'ba4b1f6efbdb7bd7c328510115f8fab9',
director_1   |   machineId: 'b27c5f44-18c5-4e2a-9a89-b9357e02836c' }

**Comment by danielvianna** [comment]
I fixed the issue, I need to hardcode the IP on the docker files as opposed to using localhost for Digital Ocean Ubuntu.
While in windows this is not necessary.
Any ideas on why this happens?

**Comment by agoldis** [comment]
The dashboard contacts the API to fetch the data, the address of the machine is defined for dashboard at 

```
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
```


If the api is not accessible by the dashboard at the provided address, it won't work. 

I didn't work on Digital Ocean before but if you can dynamically obtain and use ip / dns of the api, that would solve the problem.

**Comment by agoldis** [comment]
@danielvianna Tell me if you need any help, and if I can close the issue.

**Comment by danielvianna** [comment]
You can close no problem

**Comment by anilpujaraofficial** [comment]
@agoldis   how to generate video in localhost sorry cypress dashboard
