### ISSUE TITLE
AWS Tutorial: Unable to deploy stack in AWS 

### ISSUE THREAD

**Issue by natkrish** [agoldis/sorry-cypress#73]
Hi ,
I am trying to set up the stack in AWS - I went through your tutorial and it seemed pretty straight forward. So I did click through few buttons on screen but unfortunately it kept saying ROLLBACK IN PROGRESS> Any help much appreciated 
![image](https://user-images.githubusercontent.com/12541984/81668107-0b7e5a00-943c-11ea-8ded-2e0db8de2a9d.png)

**Comment by agoldis** [comment]
@natkrish can you please provide more details? Click throughout the tabs to see what resources failed the setup

**Comment by natkrish** [comment]
@agoldis So i think i didnt get time to explore more about the failure in AWS so I moved on to install it locally. But I have another problem in local. When I try to do the necessary steps on \packages\director 
npm install - this went through fine 
npm run build - FAILED
![image](https://user-images.githubusercontent.com/12541984/81941678-0d3d4e80-95f1-11ea-9a8a-e158cb44b572.png)
so i am unable to start the director service 
I am on windows 10 x64bit 
Node V 12.16.1

**Comment by agoldis** [comment]
@natkrish it won't take much time to re-run cloud formation template, we just need to see the error message in "Events" tab.

Also, I was able to install build "director" service - looking at the error message, it seems there's a global Mocha installed and its type definition interfere with jest package. You could just run `npm run build:js` - that will skip TS check. 

Another alternative you docker-compose files.

**Comment by agoldis** [comment]
@natkrish Are we good to close this?

**Comment by jeansymolanza** [comment]
Is there a Cloudformation template for deploying the Director service specifically? I currently am experiencing the same issues as above, I can't deploy the stack to AWS. I am only interested in the Director however.

**Comment by agoldis** [comment]
@jeansymolanza what specific error are you seeing? The only template I have includes all 3 services. You can edit it and remove unnecessary service containers.

**Comment by jeansymolanza** [comment]
This is from my most first run:

![image](https://user-images.githubusercontent.com/12545590/82741630-30cc6b80-9d4c-11ea-95fd-75dc40b15f97.png)

I have never had the bucket `sorry-cypress-test-results` created in the past. So I am unsure why it failed.

**Comment by jeansymolanza** [comment]
> @jeansymolanza what specific error are you seeing? The only template I have includes all 3 services. You can edit it and remove unnecessary service containers.

I can have a look but I’m a bit uneasy about tweaking something that I don’t understand too well. What needs to be removed from the template in order to just deploy a vanilla director configuration to AWS (as with the Heroku deployment)?

I have raised a separate issue wherein I had a CodeBuild configuration that pointed to Heroku instance but unfortunately that doesn’t work.

**Comment by agoldis** [comment]
@jeansymolanza as for the cloudformation, you'll need to provide a unique name for the stack - it fails while creating S3 bucket `sorry-cypress-test-results`. 

<img width="1340" alt="Screen Shot 2020-05-23 at 4 08 13 PM" src="https://user-images.githubusercontent.com/1637928/82742231-415ef080-9d10-11ea-8487-f974f10d202d.png">

S3 requires bucket names to be unique globally, someone has already taken that name.

**Comment by jeansymolanza** [comment]
Thanks didn’t realise that. I thought it was scoped at account level. I’ll give it a go.

**Comment by agoldis** [comment]
As for CF template with director only, I will have to test what exactly record have to be removed. If you're looking to reduce costs, removing the secondary services won't help because you're getting charged for resources, and all three services use the same ECS "node" and you'll still need a load balancer to use DNS names for accessing the service.

**Comment by agoldis** [comment]
Closing the issue, please let me know if you need any help
