### ISSUE TITLE
Suggestion: easy update of api_url

### ISSUE THREAD

**Issue by MeStrak** [agoldis/sorry-cypress#76]
Hey, great project!

I think I found an easier way to update the api_url. This will replace any occurences in app.yml. That includes the development one but it could probably be updated to change only production if required.

`sed -i -e 's|api_url:.*$|api_url: "https://sorry-cypress-demo-director.herokuapp.com/"|g' /*/.cache/Cypress/*/Cypress/resources/app/packages/server/config/app.yml`

**Comment by agoldis** [comment]
@MeStrak documentation updated https://github.com/agoldis/sorry-cypress#Using-one-liner thanks for your contribution
