### ISSUE TITLE
Thank you for creating this project

### ISSUE THREAD

**Issue by huskywhale** [agoldis/sorry-cypress#83]
I used this recently at work and it worked really well.
I even blog posted about it 
https://medium.com/@adityahbk/cypress-parallelization-on-jenkins-using-sorry-cypress-197a86ad8ed1?sk=a4af35eb5fc655a75980f66b2c7c1901

**Comment by agoldis** [comment]
Great! Thanks for posting here. I will share a link to your publication in Readme, ok?

**Comment by huskywhale** [comment]
Thank you, that's super nice of you!
