### ISSUE TITLE
Demo website is broken

### ISSUE THREAD

**Issue by mihai-cindea** [agoldis/sorry-cypress#84]
The demo website seems to be down. Thanks for all the hard work!

https://sorry-cypress-demo.herokuapp.com/

**Comment by agoldis** [comment]
What issue are you seeing with the demo site?

**Comment by mihai-cindea** [comment]
this is all i see? Not sure exactly how it should look like though so please correct me if i'm wrong.

![image](https://user-images.githubusercontent.com/56123381/85883193-e1f97200-b7e0-11ea-95f2-07f41365507a.png)

**Comment by agoldis** [comment]
Fixed
