### ISSUE TITLE
S3: 403 Forbidden

### ISSUE THREAD

**Issue by ten-aps** [agoldis/sorry-cypress#85]
Hi,

Getting an 403 when dashboard is trying to retrieve the screenshot/video file. Here is the policy I have set up on the S3 side

 "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::<S3_BUCKET_NAME>/*"

If you can help me with this, that would be great.

**Comment by agoldis** [comment]
Sure! let's start by:

1. Make sure files are in the bucket
2. Examine specific file permissions
3. Try to read a specific file using the same url that's the dashboard is using (use your browser devtools to see the network request)

Please tell me what you've found.

**Comment by ten-aps** [comment]
Sorry I have limited access to the s3 bucket, since it configured by devOps person. Also I am new to aws!

Using the CLI i am not able to see the files ( ex. - aws s3 cp s3://bucket_name/196216a2-933e-46bc-b80a-2e1dd78a01d8.mp4 ~/Downloads 
Getting - fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden ). Does this means that files does not even exists?  

Using the dev tools I am seeing this 
![image](https://user-images.githubusercontent.com/44975251/85959562-316ba980-b96b-11ea-993d-65acad2a5fcf.png)

When using the Direct URL, I am getting this 

![image](https://user-images.githubusercontent.com/44975251/85959778-5e6c8c00-b96c-11ea-97fa-d25b61fa2853.png)

**Comment by agoldis** [comment]
That means that the account you're trying to use for CLI command does not have permissions to access the stored object.

Here's an example from sorry-cypress demo: 
https://sorry-cypress-demo.herokuapp.com/instance/94e812c5-5320-4668-b224-db6452b980c4/test/r5 

AWS S3 configuration:
<img width="1184" alt="Screen Shot 2020-06-28 at 10 35 58 PM" src="https://user-images.githubusercontent.com/1637928/85976672-e0ba7780-b98f-11ea-953a-30f6cdb635a1.png">
<img width="1184" alt="Screen Shot 2020-06-28 at 10 35 54 PM" src="https://user-images.githubusercontent.com/1637928/85976674-e1530e00-b98f-11ea-9659-5e1de56350ba.png">
<img width="1187" alt="Screen Shot 2020-06-28 at 10 35 47 PM" src="https://user-images.githubusercontent.com/1637928/85976677-e1eba480-b98f-11ea-9a76-64b2698ff361.png">



<img width="1188" alt="Screen Shot 2020-06-28 at 10 36 06 PM" src="https://user-images.githubusercontent.com/1637928/85976666-de581d80-b98f-11ea-8085-50dc8d5f70a0.png">

**Comment by ten-aps** [comment]
Thanks for all the help, seems like DevOps had the configuration incorrect. This issue has been resolved
